version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ~/Documents/work/:/working
      - ./nginx/vhost/:/etc/nginx/conf.d/
      - /tmp/:/logs/
    container_name: vp_nginx
    networks:
      app:
        aliases:
          - api.local.vpgame.cn
          - api71.local.vpgame.cn
          - www.local.vpgame.cn
          - yii-webapi.local.vpgame.cn
          - webapi.local.vpgame.cn
          - admin.local.vpgame.cn
          - passport.local.vpgame.cn

  php70:
    image: 192.168.12.253:5000/php70
    volumes:
      - ~/Documents/work/:/working
      - ./php/7.0/php.ini:/usr/local/etc/php/php.ini
    container_name: vp_php70
    networks:
      - app
  php71:
    image: 192.168.12.253:5000/php71
    volumes:
      - ~/Documents/work/:/working
      - ./php/7.1/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app
    container_name: vp_php71
  php5:
    image: 192.168.12.253:5000/php54
    volumes:
      - ~/Documents/work/:/working
      - ./php/5.4/php.ini:/usr/local/etc/php/php.ini
    container_name: vp_php54
    networks:
      - app
  mysql:
    image: daocloud.io/library/mysql:5.7.4
    ports:
     - 3306:3306
    volumes:
     -  ~/Documents/mysql:/var/lib/mysql
     -  ./mysql/my.cnf:/usr/local/mysql/my.cnf
     -  ./mysql/net-tools-1.60:/tmp/net-tools-1.60
    container_name: mysql
    environment :
      MYSQL_ROOT_PASSWORD : root
    networks:
      - app
  portainer:
    image: portainer/portainer
    ports:
      - 9900:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock 
    container_name: prtainer
    networks:
      - app

  # php7.0代码静态检查/代码美化
  # php7CSMD:
  #   image: 192.168.12.253:5000/php-cs-md
  #   volumes:
  #     - ~/Documents/work/:/working
  #   container_name: vp_php_cs_md

networks:
  app:
