version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ../:/working
      - ./nginx/vhost/:/etc/nginx/conf.d/
      - /tmp/:/logs/
    container_name: api.local.vpgame.cn
    networks:
      - app
  
  php7:
    build: 
      context: .
      dockerfile: ./php/7.1/Dockerfile
    volumes:
      - ../:/working
      - ./php/7.1/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app
  
  php5:
    build: 
      context: .
      dockerfile: ./php/5.6/Dockerfile
    volumes:
      - ../:/working
      - ./php/5.6/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app

networks:
  app:
