version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ~/Documents/work/:/working
      - ./nginx/vhost/:/etc/nginx/conf.d/
      - /tmp/:/logs/
    container_name: vp_nginx
    networks:
      app:
        aliases:
          - api.local.vpgame.cn
          - api71.local.vpgame.cn
          - www.local.vpgame.cn
          - yii-webapi.local.vpgame.cn
          - webapi.local.vpgame.cn
          - admin.local.vpgame.cn
          - passport.local.vpgame.cn
  php70:
    build:
      context: .
      dockerfile: ./php/7.0/Dockerfile
    volumes:
      - ~/Documents/work/:/working
      - ./php/7.0/php.ini:/usr/local/etc/php/php.ini
    container_name: php70
    networks:
      - app
  php5:
    image: php5.4-fpm:latest
    volumes:
      - ~/Documents/work/:/working
      - ./php/5.4/php.ini:/usr/local/etc/php/php.ini
    container_name: php54
    networks:
      - app
  mysql:
    image: daocloud.io/library/mysql:5.7.4
    ports:
     - 3306:3306
    volumes:
     -  ~/Documents/mysql:/var/lib/mysql
     -  ./mysql/my.cnf:/usr/local/mysql/my.cnf
     -  ./mysql/net-tools-1.60:/tmp/net-tools-1.60
    container_name: mysql
    environment :
      MYSQL_ROOT_PASSWORD : root
    networks:
      - app
  portainer:
    image: portainer/portainer
    ports:
      - 9900:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock 
    container_name: prtainer
    networks:
      - app
  node:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/node:latest'
    container_name: nodejs
    labels:
      kompose.service.type: nodeport
    # command: sh -c 'npm install && npm start'
    ports:
      - 3000:3000
    volumes:
      - ./nodejs:/app
    networks:
      - app
  # gitlab:
  #   build:
  #     context: .
  #     dockerfile: ./gitlab/Dockerfile
  #   container_name: gitlab
  #   volumes:
  #     - ./data/gitlab/config:/etc/gitlab
  #     - ./data/gitlab/logs:/var/log/gitlab
  #     - ./data/gitlab/data:/var/opt/gitlab
  #   ports:
  #     - 443:443
  #     - 22:22
  #     - 82:80
  #   networks:
  #     app:
  #       aliases:
  #           - dome.gitlab.cn
  # jenkins:
  #     build: 
  #       context: .
  #       dockerfile: ./jekins/Dockerfile
  #     container_name: jenkins
  #     volumes:
  #         - ./data/jenkins:/var/jenkins_home 
  #     ports:
  #       - 8081:8080
  #     networks:
  #        app:
  #         aliases:
  #           - dome.jenkin.cn
  soar:
      build: 
        context: .
        dockerfile: ./soar-web/Dockerfile
      container_name: soar-web
     # volumes:
      ports:
        - 5077:5077
      networks:
        app:
          aliases:
              - dome.5077.cn
networks:
  app:
