version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ~/Documents/work/:/working
      - ./nginx/vhost/:/etc/nginx/conf.d/
      - /tmp/:/logs/
    container_name: nginx
    networks:
      - app
  php70:
    build:
      context: .
      dockerfile: ./php/7.0/Dockerfile
    #image: k8s/php7
    volumes:
      - ~/Documents/work/:/working
      - ./php/7.0/php.ini:/etc/php/php.ini
    container_name: php70
    networks:
      - app
  php5:
    image: php5.4-fpm:latest
    volumes:
      - ~/Documents/work/:/working
      - ./php/5.4/php.ini:/usr/local/etc/php/php.ini
    container_name: php54
    networks:
      - app
  mysql:
    image: daocloud.io/library/mysql:5.7.4
    ports:
     - 3306:3306
    volumes:
     -  ~/Documents/mysql:/var/lib/mysql
     -  ./mysql/my.cnf:/usr/local/mysql/my.cnf
     -  ./mysql/net-tools-1.60:/tmp/net-tools-1.60
    container_name: mysql
    environment :
      MYSQL_ROOT_PASSWORD : root
    networks:
      - app
  portainer:
    image: portainer/portainer
    ports:
      - 9900:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock 
    container_name: prtainer
    networks:
      - app
  # gitlab:
  #   build:
  #     context: .
  #     dockerfile: ./gitlab/Dockerfile
  #   container_name: gitlab
  #   volumes:
  #     - ./data/gitlab/config:/etc/gitlab
  #     - ./data/gitlab/logs:/var/log/gitlab
  #     - ./data/gitlab/data:/var/opt/gitlab
  #   ports:
  #     - 443:443
  #     - 22:22
  #     - 82:80
  #   networks:
  #     app:
  #       aliases:
  #           - dome.gitlab.cn
  # jenkins:
  #     build: 
  #       context: .
  #       dockerfile: ./jekins/Dockerfile
  #     container_name: jenkins
  #     volumes:
  #         - ./data/jenkins:/var/jenkins_home 
  #     ports:
  #       - 8081:8080
  #     networks:
  #        app:
  #         aliases:
  #           - dome.jenkin.cn
  registry:
   image: registry:latest
   container_name: registry
   volumes:
    - ~/Documents/data/registry:/var/lib/registry
   restart: always
   ports:
     - 5000:5000
   networks:
     - app
  # soar:
  #     build: 
  #       context: .
  #       dockerfile: ./soar-web/Dockerfile
  #     container_name: soar-web
  #     ports:
  #       - 5077:5077
  #     networks:
  #       app:
  #         aliases:
  #             - dome.5077.cn
networks:
  app:



